### ISSUE TITLE
Link tags always get inserted

### ISSUE THREAD

**Issue by OctoNezd** [drolsen/webpack-favicons#18]
Library inserts link tags instead of meta tags for me, breaking manifest, theme-color and probably other things.

Supposed line at fault: https://github.com/drolsen/webpack-favicons/blob/f1d12eb313e03fb309f5c18498dd0178e99da0ca/index.js#L104

There should be automatic detection of whether line is meta or link.

**Comment by drolsen** [comment]
I've included a fix for this in the 1.5.0 release that should resolve the noted issue.
However please note that the minimum node version requirement under 1.5.0 has been bumped from 14.17.0 to 18.17.0.

Thanks!
