### ISSUE TITLE
 Update version of `favicons` to resolve security issues

### ISSUE THREAD

**Issue by nodeg** [drolsen/webpack-favicons#22]
- `xml2js` is vulnerable to prototype pollution. 
- `sharp` is vulnerable to Command Injection in post-installation over build environment

A version update of `favicons` uses a more recent version of `xml2js` that is not affected anymore.

**Comment by drolsen** [comment]
This should now be resolved in the 1.5.0 version.
Please note that 1.5.0 however has bumped its minimum node version requirement up from 14.17.0 to 18.17.0.

Thanks!
